name: Pre-commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [
          "3.11",
          "3.12-dev",
        ]
        operating-system:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ChemunitedDrive
        run: |
          python -m pip install .[all]
          pip freeze

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run mypy
        run: mypy ./src

      - name: Run ruff
        run: ruff check src
